HOWTO.md, package.json
=> Document and require ID setting

lib/bridge.js
Add onAliasQueried to retrieve a room ID after creation via onAliasQuery.
=> Add onAliasQueried

lib/components/state-lookup.js, lib/exports.js, spec/unit/state-lookup.spec.js
This is designed in part to fix https://github.com/matrix-org/matrix-appservice-irc/issues/41 - but is a generally useful component for Bridges to have access to.
=> Add `StateLookup` component

lib/components/room-bridge-store.js, scripts/upgrade-db-0.3-to-1.0.js
* Added a script to help AS authors upgrade databases from 0.3 to 1.0
* Update documentation in `room-bridge-store.js` to more accurately reflect the data shape it creates
=> DB upgrade script

lib/components/intent.js
This would be useful in the slack bridge:
https://github.com/matrix-org/matrix-appservice-slack/blob/master/lib/BridgedRoom.js#L38
=> Provide an Intent method for getProfileInfo()

lib/bridge.js
* Fix markup
* Accurately document the list-of-objects return values
=> Small fixes to 3PE lookup metadata docs

lib/components/prometheusmetrics.js
Fix for https://github.com/matrix-org/matrix-appservice-gitter/issues/32
(Quite why this didn't fail for me locally I have *no* idea.. :/ )
=> Make sure to pass the correct 'this' into counter-wrapped MatrixClient

lib/components/state-lookup.js
Fixes #26 
See also
https://github.com/matrix-org/matrix-appservice-slack/blob/master/lib/MatrixSlackBridge.js#L21
https://github.com/matrix-org/matrix-appservice-gitter/blob/master/lib/Main.js#L25
=> Add StateLookup.untrackRoom() method

lib/components/app-service-bot.js
https://github.com/matrix-org/synapse/pull/1680
- `/joined_rooms`
- `/rooms/$room_id/joined_members`
=> Implement new membership list APIs

package.json, spec/integ/bridge.spec.js, spec/log.js, spec/support/jasmine.json, spec/unit/app-service-bot.spec.js, spec/unit/intent.spec.js, spec/unit/request-factory.spec.js, spec/unit/state-lookup.spec.js
Required so we can mock out Dates correctly, which is needed for testing Intent sharing logic.
=> Upgrade to Jasmine 2.5

.eslintrc, lib/components/intent.js
I think that's fairly sane?
Fixes #71
=> Don't resolve _ensureRegistered if we cannot ensure a user is registered.

lib/components/intent.js, package.json
Bump matrix-appservice to 0.3.4
Bump js-sdk to 0.10.6
Add prom-client (why didn't we want this before?)
=> Dependency updates

lib/components/agecounters.js, spec/unit/agecounters.spec.js
And it's even got tests, check that out!
Fixes #81
=> Improve AgeCounters to allow you to set any period

lib/components/intent.js, package.json
This PR is for the future when js-sdk 0.10.9 arrives with this function included. At the moment we are manually calling the http endpoint.
=> Use fetchRoomEvent

README.md, lib/bridge.js, lib/components/cli.js, lib/components/logging.js, lib/exports.js, package.json
This one is based off gitter's logger. It optionally depends on winston but will use the console if winston is not available.
=> Add Logging component

lib/models/users/matrix.js, spec/unit/matrix-user.spec.js
...if the user contains characters not supported by matrix.
=> Escape userid

lib/components/config-validator.js, package.json
This is awaiting me doing a release for matrix-appservice-node, but anyway this resolves a lot of our security issues.
=> Bump packages and replace jayschema

lib/components/membership-cache.js
=> Don't consider a user registered if they are banned or invited

lib/bridge.js, spec/integ/bridge.spec.js
(There were also a handful of cleanups)
Not sure why I didn't describe what this was fixing. The intention of the change is to allow bridges to opt out of escaping their userids.
~~ Will fix #99 ~~
=> Escape userids part2

lib/models/users/matrix.js
As per https://matrix.org/docs/spec/appendices.html#identifier-grammar
=> disallow uppercase userids

lib/models/users/matrix.js
I didn't get my coffee and merged the wrong thing
=> Revert "disallow uppercase userids"

.eslintrc.json
=> Require ECMAScript 2017

package.json
=> Replace istanbul by nyc

.travis.yml
=> Make Travis use Node 8

lib/bridge.js
Fix some small bugs related to error handling that sneaked in.
=> Fix bridge error handling

lib/components/room-upgrade-handler.js
Couple of things that I missed.
=> Fixes for removing old entries

src/bridge.js
This fixes e.g. databases being created while disabled stores
Signed-off-by: Laurin Benz <witchent@posteo.de>
=> Fixed two disableStores->opts.disableStores

changelog.d/171.bugfix, spec/integ/bridge.spec.js, spec/unit/intent.spec.js, src/components/cli.js, src/components/intent.js, src/index.ts
We bumped to matrix-js-sdk 6, but there were a few problems.
=> Fix ContentRepo and .done() calls to matrix-js-sdk

changelog.d/226.misc, package.json, src/bridge.ts
Migrations:
- https://github.com/matrix-org/matrix-appservice-node/pull/27.
=> Upgrade to the next version of matrix-appservice

changelog.d/227.feature, src/bridge.ts
=> Add close function

changelog.d/236.bugfix, src/bridge.ts, src/components/event-types.ts
=> Weak event should allow state_key and unsigned to be optional

changelog.d/237.feature, package-lock.json, package.json
Probably shouldn't sit on the RC forever.
=> Update JS SDK to v8.4.1

changelog.d/247.bugfix, src/bridge.ts
=> Fix alias queries not arriving through the bridge

changelog.d/270.bugfix, package-lock.json, package.json, spec/integ/cli.spec.js, src/bridge.ts, src/components/app-service-bot.ts, src/components/cli.ts
Update `matrix-appservice` dependency for registration fixes
Includes https://github.com/matrix-org/matrix-appservice-node/pull/34
=> Update matrix-appservice dependency for registration fixes

HOWTO.md, changelog.d/272.doc, examples/slack-starter/src/index.ts
=> Remove references to user_id

README.md, changelog.d/273.misc
=> Remove TravisCI badge

changelog.d/299.feature, src/bridge.ts
=> Split out Bridge.run to two functions

changelog.d/303.misc, package-lock.json, package.json
=> Update matrix-js-sdk 

changelog.d/302.bugfix, src/components/logging.ts
=> Ensure bridge does not log by default

changelog.d/301.feature, src/components/intent.ts
=> Add resolveRoom function
