matrix-org/matrix-appservice-bridge

- lib/components/room-bridge-store.js
- spec/integ/room-bridge-store.spec.js
Specifically:
- `RoomBridgeStore.batchGetRemoteLinks`
- Do not query for mappings if there are no IDs to search on.
> Implement store optimisations

- lib/components/room-bridge-store.js
- spec/integ/room-bridge-store.spec.js
As per https://github.com/matrix-org/matrix-appservice-irc/issues/68 - this PR re-implements the room store to be much more efficient. It does this by:
- Strictly having 1 entry per mapping, so fewer total documents are in the database.
- Slightly de-normalising data for multi-mapped rooms to reduce the number of queries needed to retrieve mapped room data.
This format is **not compatible** with the current format, which means this is effectively a new MAJOR version of the library.
> Reimplement the RoomBridgeStore database schema

- lib/bridge.js
- spec/integ/bridge.spec.js
This allows callers to disable the database lookups which are called for each and every incoming event.
> Add disableContext to `Bridge.opts`

- lib/bridge.js
- lib/components/client-factory.js
Previously, the bridge bot may become head-of-line blocked by it's own event scheduling back-off. This has been made less aggressive; the delay between each request to send a previously failed sending of event increases linearly now.
Also, the queuing algorithm separates queues by room ID.
Fix for https://github.com/matrix-org/matrix-appservice-irc/issues/122
> Better scheduling of events sent to HS

- lib/bridge.js
This PR adds a new `controller` feature, `onThirdPartyLookup` which helps bridges to implement the API defined in
https://docs.google.com/document/d/13NGa46a_WWno-XYfe8mQrglQdtOYMFVZtxkPKXDC3ac/edit#heading=h.m0btedxhv6ao
> Provide wrapper for 3PE lookup APIs

- lib/bridge.js
- lib/components/client-factory.js
Pass a scheduler builder function in to client factory rather than a single scheduler directly
Fixes #18
> One MatrixScheduler for every client

- lib/components/config-validator.js
Validation errors thrown by ConfigValidator have a ```_validationErrors``` property which is set to the internal errors that occurred during validation, giving a more detailed report as to what failed to validate. This is useful for showing errors to users inputting data.
> ConfigValidator throws validate error with validation errors

- lib/components/intent.js
I'd like bridges to send read receipts for the times when we get that information from the third-party network (gitter and slack for example).
> Add intent.sendReadReceipt()

- lib/bridge.js
- lib/components/agecounters.js
- lib/components/client-factory.js
- lib/components/prometheusmetrics.js
Part of #29 
* Counting of MatrixClient API calls
* Counting of intent users
* Neater wrapping of other gauge counts to simplify bridge instance code
> Begin hooking up PrometheusMetrics to core Bridge object

- lib/components/intent.js
- lib/components/prometheusmetrics.js
- lib/components/state-lookup.js
- spec/unit/app-service-bot.spec.js
Main reason being that `prom-client` supports both Histograms and Summaries; old `prometheus-client` does neither.
Also, `prom-client` does its own implementation of the standard process-wide metrics, so we can delete *aaaall* the code relating to that here.
See also #43
> Switch from `prometheus-client` to `prom-client`

- lib/components/intent.js
- spec/unit/intent.spec.js
It is possible that Synapse will not send join/leave `m.room.member`
events to the bridge which were originally sent **by** the bridge.
This breaks an assumption in the `Intent` class whereby we maintain
a membership cache which is kept up-to-date by calls to `onEvent`.
This cache can now get out of sync.
To fix this, we now have "join guards" around the sending of
message and state events. This guard intercepts failures and checks
if the `errcode` is `M_FORBIDDEN`. If it is, it will perform another
call to `_ensureJoined` but with the `ignoreCache` flag set, forcing
an HTTP hit to join the room.
Fixes matrix-org/matrix-appservice-irc#343
With UTs.
> Intent: Handle not in room failures due to a stale cache

- lib/components/intent.js
If the bridge app itself is maintaining membership state then having the library set join events too might disrupt that. E.g. currently `matrix-appservice-tg` wants to keep a per-room displayname in membership events.
> Implement a 'dontJoin' intent option

- lib/components/intent.js
Move the early-exit if `dontJoin` is set until after we've at least registered the user
> Even with dontJoin set, still ensure that the user is registered

- lib/bridge.js
- lib/components/intent.js
- package.json
- spec/integ/bridge.spec.js
- spec/unit/intent.spec.js
This has 2 notable performance implications wrt the IRC bridge:
- Prevents unbounded memory expansion as we now cull `Intent` objects.
- Prevents CPU spins that happen when all `Intent` objects are looped over when updating `m.room.member` or `m.room.power_levels` events.
Requires #54 for Jasmine 2, so is based off that PR. With tests to assert that:
- Culls happen.
- Culling doesn't result in missing state when they get remade.
> Share Intent data structures created by Bridge

- lib/components/prometheusmetrics.js
Since prom-client v9, the default process-wide metrics are not actually enabled by default. (Despite what you'd imagine by the name ;) ). So we have to explicitly enable them.
> Enable the default process-wide metrics in prom-client 9.0.0

- lib/components/intent.js
Also adds a ``Intent`` opt ``enablePresence`` which is true by default. Useful for bridges who want to disable presence support without having to go through all the presence code.
> Add Intent.setPresence

- README.md
- lib/bridge.js
- lib/components/config-validator.js
- lib/components/logging.js
- lib/components/room-link-validator.js
- spec/unit/room-link-validator.spec.js
This change adds a new class, the RoomLinkValidator. This is a rather bruteforced method of avoiding double bridged rooms by creating a rule file and setting rules about what can and can't be bridged by checking what userIds are present in the room.
~~The rule file can optionally be watched for changes, and valid changes will be applied on the fly.~~
The rule file can be reloaded by hitting the ``/_bridge/roomLinkValidator/reload`` endpoint.
> Room linking validation

- .eslintrc
- README.md
- lib/bridge.js
- lib/components/intent.js
- lib/components/room-upgrade-handler.js
- package.json
- spec/unit/room-upgrade-handler.spec.js
Fixes #95 
This works by listening for a `m.room.tombstone` event and attempts to join the referenced room (first by room_id, then by alias). If that succeeds it finds all entries by the old room id and replace with the new room id. If the join fails, it waits for a subsequent invite before trying to update the entries.
The entry update logic can be overriden by providing a callback, and bridges can hook into another callback once an upgrade has been completed.
This functionality is disabled by default and must be enabled by providing a config.
> Support room upgrades

- .eslintrc.json
- lib/components/room-link-validator.js
- package.json
- spec/integ/bridge.spec.js
Some small changes to make linting work again properly. Fixes vulnerabilites, deprecation warnings, linter errors and a superfluous comma.
- upgrade eslint `^1.2.0`→`^5.16.0`
- rename `.eslintrc`→`.eslintrc.json`
- replace eslint attribute `space-after-keywords` with `keyword-spacing`
- add explicit returns to functions where they are missing to avoid lint erros
Note: I did not fix the linter *warnings* to avoid tainting the blame.
> Repair linting

- lib/models/users/matrix.js
- spec/unit/matrix-user.spec.js
This fixes #109. In addition, this PR adds a global variable to disable userid escaping for bridges that don't support it yet.
> Escape user IDs correctly

- README.md
- lib/bridge.js
- lib/components/event-bridge-store.js
- lib/exports.js
- lib/models/events/event.js
- spec/integ/event-bridge-store.spec.js
Fixes #92 
Some bridges want to be able to store events ids long term, mapped against their bridged counterparts for things like replies and redactions. This should be a suitable starting point.
> Create an EventStore for Cadair

- .eslintrc.json
non_camel_case_vars now throw warnings when linting.
> Add camelcase check to eslint

- README.md
- lib/bridge.js
- lib/components/event-queue.js
- lib/components/intent.js
- lib/errors.js
- lib/exports.js
- spec/unit/event-queue.spec.js
- spec/unit/intent.spec.js
Adds the ability of signaling permanent errors occuring at the bridge to the SDK as well as automatic sending of these events. If the bridge rejects a room event that was handed to it, the room will automatically be notified of this error.
Mainly two things are added by this PR:
- A new method `signalBridgeError` is added to the `Intent` class.
- Rejection of requests provided to the `onEvent` callback will trigger the new intent.
Bridges should not have to do much work or work at all to profit from the new feature. Every bridge rejecting the request object delivered to it (as should be the case already) will profit. If a bridge swallows errors and simply logs them, code has to be changed to reject the request object properly.
In addition to these changes there is some refactoring and …
> Enable signaling of bridge errors

- lib/bridge.js
Catches the error of the rejected request promise and logs it as responsible for dropping the event. By this `_onEvent` will never return a rejected promise.
> Catch all request errors before returning from _onEvent

- lib/bridge.js
- lib/components/bridge-context.js
- lib/exports.js
The `BridgeContext` class is part of the public interface of the bridge (`controller.onEvent`), so it should be properly exported.
The PR also refactors the class to something appearing to be from this century.
> Export and cleanup BridgeContext

- lib/components/room-bridge-store.js
- lib/components/room-upgrade-handler.js
Bridges such as the IRC bridge store lots of information in the `entry.id` and subsequently everything gets borked on upgrade, as we don't modify the `id` of the entry. Typically how this works is that the IRC bridge will store the channel + network + **`matrix_room_id`** in the entry, and then will also try to fetch the entry based upon that string. 
Upgrades will update the entries contents, but not the id and thus everything expodes!
This PR changes things so that a changed `id` will be detected, and the old entry will be removed.
> Remove old entries during upgrade

- lib/bridge.js
This change makes it so that we:
- Do not log when we drop events, the bridge itself can handle that.
- Always return the result of the request, as it's expected behavior
- Continue to report errors asynchronously 
- Do not send bridge errors when we fail to get context, because that's unhelpful.
> Always return request result when handing errors

- lib/bridge.js
This fixes a bug where some bridges would rely on errors falling through for testing, which we would filter out accidentally.
> Always return promises when handing events

- lib/bridge.js
- lib/components/room-upgrade-handler.js
- spec/integ/bridge.spec.js
- spec/unit/room-upgrade-handler.spec.js
We've made various hacks in some of the bridges to disable calls to the stores when we switched to other storage mechanisms, but this PR adds a switch to disable store access entirely within the bridge without causing breakages.
Where needed, this PR has refactored some functions into `async function`s for readability
> Add option to disable stores

- lib/bridge.js
- spec/integ/bridge.spec.js
This has been a long requested feature, because presently bridges will bind to `0.0.0.0` which tends to leave everything quite exposed.
Fixes https://github.com/matrix-org/matrix-appservice-bridge/issues/113
> Allow bridges to bind to a hostname

- HOWTO.md
IMHO it was not clear that localhost is the servername.
(Because in the note which says that the AS user must be invited if the room ist non-public the example userid is `@slackbot:domain` not `:localhost`)
> Add note: replace localhost with server_name

- lib/bridge.js
- lib/components/intent.js
- spec/integ/bridge.spec.js
- spec/unit/intent.spec.js
Which in practice is just `user_id`.
Will also depend on https://github.com/matrix-org/matrix-appservice-node/pull/20, when it lands.
~This will require a version bump to 2.0 as existing bridges may depend on the user_id behavior.~ Actually, it won't. Synapse will send bridges V2 events regardless of the version of this library, so meh.
> Remove usages of the v1 event format keys

- .eslintrc.json
- .travis.yml
PR to bump the minimal required node.js version to 10. This is mainly to support object rest and spread properties.
Signed-off-by: Kai A. Hiller <KaiAlexHiller@web.de>
> Bump node.js version to 10

- src/components/cli.js
This isn't needed, and is misleading.
> Remove '/appservice'

- src/bridge.js
- src/components/prometheusmetrics.js
This fixes a bug where we were previously not checking the hsToken on several bridge endpoints.
> Authenticate requests to bridge endpoints

- src/bridge.js
Missed from #158. Ensure we only allow v1 or unstable requests to these endpoints.
> Limit versions to v1/unstable

- src/bridge.js
Missed this during testing. `express` lowercases header names :/
> Header is lowercase

- changelog.d/168.feature
- pyproject.toml
- scripts/changelog-check.sh
- scripts/changelog-release.sh
Because towncrier is awesome and we should start using it here.
> Add towncrier files

- changelog.d/169.feature
- src/bridge.js
- src/components/prometheusmetrics.ts
This allows us to provide a alternative register for bridges, for example a threaded register on a different worker thread :). This change also allows bridges to opt out of binding /metrics to the appservice server.
> Add support for alternative registers for metrics

- changelog.d/164.feature
- src/components/cli.js
This PR switches to storing the parsed arguments as an instance variable, so that once parsed, bridges are able to use getArgs() to get access to the parsed arguments for the bridge.
One example use case is retrieving the location of the configuration file, which did not seem possible otherwise, for passing to other libraries which need to read and update the JSON for themselves (example, matrix-puppet-bridge).
Signed-off-by: James Hebden <james@ec0.io>
> Make parsed arguments accessible to bridges

- changelog.d/150.bugfix
- src/components/logging.js
If you log before loggers are setup, but never actually log to that logger again, it just never logs.
Quick patch to drain the log queue as soon as things are setup.
It also could be done on setLogger
> Drain the queue after setting up logger

- .eslintrcts.json
- changelog.d/177.misc
- src/components/event-queue.ts
This is a fairly easy candidate to port, as it was using ES6 classes already.
> Typescriptify event queue

- src/bridge.js
In the function loadDatabase we use `const defer = defer()`. This means the second `defer` is not the imported function, but the undefined variable of the local scope.
> Fix usage of deferPromise

- changelog.d/191.bugfix
- spec/integ/bridge.spec.js
- src/bridge.js
Fixes #192 
This allows for errors of `.listen` to bubble up and get handled.
> Await for a Bridge to listen to its port

- changelog.d/197.misc
- package.json
Just like https://github.com/matrix-org/matrix-appservice-node/pull/25, we don't use it.
> Drop request library

- changelog.d/194.feature
- package-lock.json
- package.json
- src/components/intent.ts
- src/components/request-factory.ts
- src/components/state-lookup.ts
- src/index.ts
- tsconfig.json
This is a collection of changes needed to make our types work with the IRC bridge. We should either merge this into the parent PR (and subsequently into that one), or find a way to include these changes.
> Type fixes needed to make matrix-appservice-irc build

- changelog.d/201.bugfix
- src/components/prometheusmetrics.ts
This bug caused the irc bridge to provide no metrics.
> Use provided register for metrics

- changelog.d/207.feature
- spec/integ/cli.spec.js
- src/components/cli.ts
This allows bridge developers to listen for config changes, which can be bubbled up to the bridge logic to support small changes without restarting the whole bridge. This is useful for things like the irc bridge, where restarts are costly.
I've also added some minimal Cli tests to ensure that config behaviour continues to work as expected.
> Add ability to watch config for changes

- changelog.d/216.feature
- package-lock.json
- package.json
- scripts/upgrade-db-0.3-to-1.0.js
- spec/integ/bridge.spec.js
- spec/unit/client-request-cache.spec.js
- spec/unit/state-lookup.spec.js
- src/bridge.ts
- src/components/event-queue.ts
- src/components/state-lookup.ts
- src/utils/promiseutil.ts
This is a breaking change to enforce the use of **pure** Bluebird promises. Since we've already made breaking changes in other areas of the library, we might as well remove the use of these as well.
> Remove bluebird dependency

- changelog.d/217.feature
- src/components/cli.ts
The bridge may instead choose to let the user configure the url.
Fixes #182
> Make url parameter optional when generating registration

- changelog.d/218.misc
- package.json
- spec/integ/bridge.spec.js
- src/bridge.ts
- src/components/agecounters.ts
- src/components/app-service-bot.ts
- src/components/logging.ts
- src/components/room-bridge-store.ts
- src/index.ts
- src/models/users/matrix.ts
- src/models/users/remote.ts
- src/thirdparty.ts
This PR is a mixed bag of small code changes to ensure compatibility with existing bridges. Care has been taken to lean towards updating the IRC bridge where possible, rather than porting bad behaviours back into this SDK.
> Various type improvements to improve compatibility with existing bridges

- src/components/cli.ts
We need to separate the Opts type as a parameter from it as an internal variable.
The parameter has optional properties which the internal type assumes to be there because we have defaults for them. Using the same type makes these properties seem non-optional to the outside.
> Fix types: CliOpts

- HOWTO.md
- changelog.d/225.misc
- changelog.d/226.misc
- examples/slack-starter/.gitignore
- examples/slack-starter/package-lock.json
- examples/slack-starter/package.json
- examples/slack-starter/src/index.ts
- examples/slack-starter/tsconfig.json
- src/bridge.ts
This PR corrects the types of `opts` in `new Bridge(opts)` for software that uses this library – one example project was also added.
The parameter `opts` of `Bridge` has some optional properties that are required on the internal type opts.
That's why I'm now splitting them into two types – similar to how it was done in #222.
In the long term, I would like these opts to become direct properties of `Bridge` instead of being stored in the `this.opts` object.
> VettedOpts for Bridge & Example: slack-starter

- changelog.d/232.bugfix
- src/components/intent.ts
We use this in various places on the Slack bridge to get the full profile of a user.
> Allow info to be null on getProfileInfo

- changelog.d/233.bugfix
- src/bridge.ts
- src/components/client-factory.ts
- src/components/intent.ts
The bridge bot cannot sync and should never encrypt its messages. Ensure the bridge bot goes via the homeserver URL, while ghosts use the E2E proxy.
> Use actual homeserver URL for the bridge bot

- changelog.d/242.misc
- src/components/intent.ts
This should be non-breaking, as this only updates the types.
> Return event_id when sending a message

- changelog.d/276.feature
- src/components/membership-queue.ts
Fixes #259 
This PR creates 3 new metrics entries for prometheus:
- `membershipqueue_pending(type)` which will show which types of membership are waiting in the queue
- `membershipqueue_processed(type, outcome)` will show the number of completed (success & failed) membership actions
- `membershipqueue_reason(type, errcode, http_status)` will be a count of the failures for the actions
- `membershipqueue_lastage` is the age of the last processed request, in MS
Output looks good:
```
bridge_membershipqueue_pending{type="leave"} 0
bridge_membershipqueue_pending{type="kick"} 0
bridge_membershipqueue_pending{type="join"} 0
bridge_membershipqueue_processed{type="leave",outcome="success"} 6
bridge_membershipqueue_processed{type="kick",outcome="success"} 4 …
```
> Add membership queue metrics

- changelog.d/292.misc
- src/bridge.ts
- src/components/client-factory.ts
- src/components/room-link-validator.ts
- src/components/room-upgrade-handler.ts
Adds return type annotations and fixes a few grammatical mistakes.
> Be more explicit about return types

- changelog.d/285.bugfix
- src/bridge.ts
- src/components/encryption.ts
- src/components/intent.ts
- src/components/prometheusmetrics.ts
Fixes #284
Depends on #295 
Sometimes we get into a state where the bridge isn't reliably syncing messages from client's and so ends up in a broken state, this aims to fix that.
> Encryption improvements

- changelog.d/300.bugfix
- src/components/membership-cache.ts
- src/components/membership-queue.ts
> Add "type" to membership queue metrics

- changelog.d/316.removal
- changelog.d/320.removal
Note: This will actually be removed when we do a release, but the note must come first.
> Remove master branch

- changelog.d/330.bugfix
- src/components/room-upgrade-handler.ts
The room upgrade code previously did not check to see if the new room ID referred back to the old room ID when traversing an upgrade.
> Check m.room.create event on room upgrade

- changelog.d/371.bugfix
- src/components/membership-queue.ts
Fixes #370  
This usually means the room doesn't exist for ex: https://github.com/matrix-org/synapse/blob/c01bc5f43d1c7d0a25f397b542ced57894395519/synapse/handlers/room_member.py#L812.
> Do not retry membership on a 404 error
